language: haxe

haxe:
  - 3.4.7

env:
  - TARGET=flash OPENFL=new
  - TARGET=neko  OPENFL=new
  - TARGET=cpp   OPENFL=new
  - TARGET=html5 OPENFL=new
  - TARGET=flash OPENFL=old
  - TARGET=neko  OPENFL=old
  - TARGET=cpp   OPENFL=old
  - TARGET=html5 OPENFL=old

sudo: false
dist: trusty

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX

install:
  - haxelib git flixel https://github.com/HaxeFlixel/flixel
  - haxelib dev flixel-demos $TRAVIS_BUILD_DIR
  - haxelib list

script:
  - export HXCPP_COMPILE_CACHE=~/hxcache
  - cd ~/haxe/lib/flixel/git/tests
  - haxe RunTravis.hxml
  - neko RunTravis.n $TARGET $OPENFL
