language: java

before_script:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install lime
  - haxelib install lime-tools
  - haxelib run lime install openfl
  - haxelib install systools
  - haxelib install spinehx
  - haxelib install nape
  - haxelib install task
  - haxelib dev flixel-demos .
  - haxelib git firetongue https://github.com/larsiusprime/firetongue
  - haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
  - haxelib git flixel-tools https://github.com/HaxeFlixel/flixel-tools
  - haxelib git flixel-ui https://github.com/HaxeFlixel/flixel-ui dev
  - haxelib git flixel https://github.com/HaxeFlixel/flixel dev

script:
  - haxelib run flixel-tools testdemos
